name: module4_task1
on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 23 * * *"
  pull_request:
    types: [opened, edited, reopened, ready_for_review]
jobs:
  All-Validation-Code:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone the repository
        uses: actions/checkout@v3
      - name: Checkout tools
        run: make --version >/dev/null 2>&1 && echo OK
        working-directory: module4_task1
      - name: Setup tools
        run: sudo ./setup.sh
        working-directory: module4_task1
      - name: Create Docker and execute make targets
        working-directory: module4_task1
        run: |
        make build-docker
        docker run --rm -v $(pwd):/app awesome:build make clean
        docker run --rm -v $(pwd):/app awesome:build make lint
        docker run --rm -v $(pwd):/app awesome:build make build
        docker run --rm -v $(pwd):/app awesome:build make test
        docker run --rm -v $(pwd):/app awesome:build make package
        ls -la
        docker image ls | grep awesome
      - name: Upload hugo website in zip file
        if: ${{ success()}}
        uses: actions/upload-artifact@v3
        with:
          name: upload-package
          path: module4_task1/awesome-website.zip
          if-no-files-found: error
      - name: Github release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # tag_name: 1.0.1
          # body_path: module4_task1/DEPLOY.md
          files: |
            module4_task1/awesome-website.zip
            module4_task1/DEPLOY.md
