name: module3_task0
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 23 * * *"
jobs:
  Validation-Code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Makefile Validation
        run: make help
        working-directory: module3_task0
